In [2]:
import numpy as np

In [11]:
x = np.random.randn(10, 3)
y = np.random.randn(10)

In [12]:
x

array([[-1.7779962 ,  0.19853146,  0.23778656],
       [ 0.64141533, -1.3368982 ,  1.99191679],
       [ 1.69879377,  0.64847001, -2.02972031],
       [ 1.41569591,  0.33884995,  0.19275896],
       [ 0.21150504,  0.68735492,  0.71685357],
       [ 1.31780076,  0.57098502, -0.21134747],
       [ 0.27072493,  0.57297188,  0.46318015],
       [ 0.2495258 , -0.05514597, -0.2701909 ],
       [-0.61133382, -1.47884903,  1.00651454],
       [-0.5196045 ,  1.2533374 , -1.45812528]])

In [13]:
y

array([-0.31948175, -0.60969577, -1.43225591,  1.14377358, -0.20525413,
        0.58452102, -0.20711154, -1.98584903, -0.77516144,  1.27109852])

In [14]:
w1 = np.random.randn(3, 5)
b1 = np.zeros(5)
w1, b1

(array([[-3.80335600e-01,  1.80134041e+00,  7.29511514e-01,
          1.65536710e+00,  5.11525426e-01],
        [ 2.92144476e-04,  5.94903373e-01,  2.00421364e-02,
          1.59611772e+00,  1.88325531e+00],
        [-3.16781198e-01, -2.60326968e-01,  3.40013349e+00,
         -7.84725816e-01, -1.58403387e+00]]), array([0., 0., 0., 0., 0.]))

In [15]:
w2 = np.random.randn(5, 1)
b2 = np.zeros(1)
w2, b2

(array([[ 0.42216265],
        [-0.09277455],
        [-0.71966734],
        [ 1.20353958],
        [-0.76768458]]), array([0.]))

In [16]:
def lin(x, w, b):
  return x@w + b

In [17]:
def relu(x):
  return np.maximum(x, 0)

In [18]:
def forward(x, w1, b1, w2, b2):
  a1 = lin(x, w1, b1)
  print(a1.shape)
  x2 = relu(a1)
  print(x2.shape)
  a2 = lin(x2, w2, b2)
  return a2

In [19]:
out = forward(x, w1, b1, w2, b2)
out

(10, 5)
(10, 5)


array([[ 0.25370579],
       [-5.19161436],
       [ 2.10562611],
       [ 1.00750334],
       [-1.07136325],
       [ 1.88214894],
       [-0.51831093],
       [ 0.25437259],
       [-2.12062174],
       [-0.37050517]])

In [26]:
def mse(inp, targ):
  return np.mean((inp.squeeze(1)-targ)**2)

In [187]:
(y-out.squeeze(1))

array([1.28741348, 2.11100578, 1.6502652 , 2.57710496, 3.70565303,
       2.55043151, 2.1423987 , 9.6371785 , 0.80936452, 2.49091534])

In [188]:
(y-out.squeeze(1)) ** 2

array([ 1.65743346,  4.45634541,  2.72337522,  6.64146996, 13.73186441,
        6.50470087,  4.58987221, 92.8752094 ,  0.65507092,  6.20465921])

In [189]:
mse(out, y)

14.004000106400582

In [24]:
def out_g(inp, targ):
  return (2 * (inp.squeeze(1) - targ))[:, None] / inp.shape[0]

In [23]:
def relu_g(inp, out_g):
  return (inp>0).astype(float) * out_g

In [22]:
def lin_g(inp, out_g, w):
  inp_g = out_g @ w.T
  w_g = inp.T @ out_g
  b_g = np.sum(out_g, axis=0)  #

  return inp_g, w_g, b_g

In [28]:
def forward_backward(x, w1, b1, w2, b2, y):
  a1 = lin(x, w1, b1)
  x2 = relu(a1)
  a2 = lin(x2, w2, b2)

  loss = mse(a2, y)

  out1_g = out_g(a2, y)
  out2_g, w2_g, b2_g = lin_g(x2, out1_g, w2)
  out3_g = relu_g(a1, out2_g)
  out4_g, w1_g, b1_g = lin_g(x, out3_g, w1)

  print(loss, '\n\n', out1_g, '\n\n',out2_g, '\n\n', w2_g,  '\n\n', b2_g, '\n\n', out3_g, '\n\n', out4_g, '\n\n', w1_g, '\n\n', b1_g)

In [20]:
x.shape, w1.shape, w2.shape, b1.shape, b2.shape

((10, 3), (3, 5), (5, 1), (5,), (1,))

In [193]:
y

array([ 1.28741348, -0.81030968,  0.45697248,  0.81380649, -1.66993953,
       -0.62140601,  1.0671858 , -0.69394796, -0.63207742,  1.10506959])

In [194]:
out

array([[  0.        ],
       [ -2.92131546],
       [ -1.19329272],
       [ -1.76329847],
       [ -5.37559257],
       [ -3.17183752],
       [ -1.0752129 ],
       [-10.33112645],
       [ -1.44144194],
       [ -1.38584575]])

In [29]:
forward_backward(x, w1, b1, w2, b2, y)

4.591224790675014 

 [[ 0.11463751]
 [-0.91638372]
 [ 0.7075764 ]
 [-0.02725405]
 [-0.17322182]
 [ 0.25952558]
 [-0.06223988]
 [ 0.44804432]
 [-0.26909206]
 [-0.32832074]] 

 [[ 0.04839567 -0.01063544 -0.08250087  0.13797078 -0.08800545]
 [-0.38686297  0.08501709  0.65949143 -1.10290408  0.70349365]
 [ 0.29871233 -0.06564508 -0.50921963  0.85159621 -0.5431955 ]
 [-0.01150564  0.00252848  0.01961385 -0.03280133  0.02092251]
 [-0.07312778  0.01607058  0.12466209 -0.20847932  0.13297972]
 [ 0.10956201 -0.02407737 -0.18677209  0.31234931 -0.19923379]
 [-0.02627535  0.00577428  0.04479201 -0.07490816  0.0477806 ]
 [ 0.18914758 -0.04156711 -0.32244287  0.53923908 -0.34395672]
 [-0.11360062  0.02496489  0.19365677 -0.32386295  0.20657783]
 [-0.13860475  0.03045981  0.23628171 -0.395147    0.25204677]] 

 [[-0.14776449]
 [ 3.46448608]
 [-7.94621186]
 [ 3.89550675]
 [ 2.94604713]] 

 [-0.24672845] 

 [[ 0.04839567 -0.         -0.          0.         -0.        ]
 [-0.          0.          0.659